unique_ids:
  assets:
    standard-page.html: ZBTXIVMFSZ2SEQ6N56FADLNST55KAZVH
    theme.css: OCK62LJ74GRZ5M7U6SOPUIPXYZKYXIVS
  forms:
    Form1: BUPGO43XA4XKBCS3ESTWQIAFUOXAZCLD
  modules: {}
  scripts: {}
  server_modules: {}
